//TODO name things in more logical groups like API requests, filtering etc
export const UPDATE_MOVIE_LIST = "UPDATE_MOVIE_LIST";
export const REQUEST_MOVIES_BY_YEAR = "REQUEST_MOVIES_BY_YEAR";
export const CHANGE_YEAR = "CHANGE_YEAR";
export const CHANGE_GENRE = "CHANGE_GENRE";
export const DISPLAY_MOVIE = "DISPLAY_MOVIE";
export const RESET_DISPLAYED_MOVIE = "RESET_DISPLAYED_MOVIE";
export const GET_GENRE_LIST = "GET_GENRE_LIST";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const ADD_MOVIE_TO_SAVED_LIST = "ADD_MOVIE_TO_SAVED_LIST";
export const REMOVE_MOVIE_FROM_SAVED_LIST = "REMOVE_MOVIE_FROM_SAVED_LIST";
export const UPDATE_SAVED_MOVIES_LIST_FROM_SERVER =
  "UPDATE_SAVED_MOVIES_LIST_FROM_SERVER";
